### ISSUE TITLE
Script does not work when it is directly installed in the root folder of a project

### ISSUE THREAD

**Issue by frastel** [chefkoch-dev/container-run#1]
Currently the script assumes that it is called from within a subfolder of a project. 

So something like

```
cd <project_root>/
curl 'https://raw.githubusercontent.com/chefkoch-dev/docker-run/master/run' -o run
./run <some command>
```

will break because the parent folder of `<project_root>` and not the root folder will be mounted to the container

**Comment by pierres** [comment]
The latest version uses the root directory of an existing git repository or the current directory as working directory.
